### ISSUE TITLE
[BUG REPORT] If attach launched tmux, the Keybindings will be broken

### ISSUE THREAD

**Issue by sachin21** [k0kubun/xremap#13] opened 2017-01-11 11:18 UTC
# Problem summary
If attach launched tmux, configured xremap's emacs keybindings will be broken. However
## System Infomation
- xremap's latest commit hash

https://github.com/k0kubun/xremap/commit/a1b6e10aa6492a18f63a24adb155db90a7693ea0

- `uname -a`
```
Linux sachin21dev 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

- `tmux -V`
```
tmux 2.3
```

## Error Messages
remapped for class: "xfce4-terminal"
remapped for class: false
unexpected event detected! (33) # Attached tmux session from this line 
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)

# Steps to Reproduce
- Lanuch xfce4-terminal
- Lanuch tmux
- `$ xremap "$HOME"/.xremap`
- Attach a session
- ** Break the Emacs keybindings **

**Comment by k0kubun** [comment] 2017-01-11 12:18
"emacs bindings" are not xremap's feature. What's the source of `~/.xremap`?

**Comment by k0kubun** [comment] 2017-01-11 12:42
I installed xfce4-terminal, fix my configuration to use `class_not: "xfce4-terminal"` about Emacs bindings and did your steps. Indeed I found "remapped for class: false" in log but this wasn't reproductive.

- Is `xremap ~/.xremap" executed in tmux session?
- Why did you write "Attach a session" after "Launch tmux"? When you launch tmux, your current shell should be attached to a tmux session. Do you open multiple terminals? If so, please write details about that.
- Is this reproductive for other terminals? Is xfce4-terminal related to this bug?
- Have you tried using systemd to execute xremap? You use Arch Linux.
- I found "unexpected event detected! (33)" when I execute multiple xremaps. Do you have any other process that remap your bindings?
- Could you try some other combinations other than Emacs bindings? I suspect some of your configuration prevent xremap from remapping C-a,C-b,....

**Comment by sachin21** [comment] 2017-01-12 05:37
Thank you for the quickly reply. And thank you so much for telling root cause on Twitter.
Root cause is ~/.gtkrc-2.0. When I removed .gtkrc-2.0, Emacs keybindings are well.
In case, I write answers.

> Is `xremap ~/.xremap" executed in tmux session?
No, Already executed xremap before attached tmux.

> Why did you write "Attach a session" after "Launch tmux"? When you launch tmux, your current shell should be attached to a tmux session. Do you open multiple terminals? If so, please write details about that.
Yeah, I launched multiple terminals for the see logs. but I think not multiple terminals is note related to this problem. I only reproduced this case on attaching tmux.

> I found "unexpected event detected! (33)" when I execute multiple xremaps. Do you have any other process that remap your bindings?

The question was talked on Twitter. https://twitter.com/k0kubun/status/819165931905527812

> Could you try some other combinations other than Emacs bindings? I suspect some of your configuration prevent xremap from remapping C-a,C-b,....

Other keybindings are successfully running.

**Comment by k0kubun** [comment] 2017-01-14 00:56
This issue isn't reproductive in written steps. It may depend on your local configuration or some unexpected application that does `XGrabKey`. Since I can do nothing for this issue, closing.

But I could notice I should do two things to improve the way to handle this kind of problem.

- https://github.com/k0kubun/xremap/issues/14
- https://github.com/k0kubun/xremap/issues/15

#15 may be alternative solution for you. I'll inform you when it's done. Thank you for reporting an issue!

**Closed by k0kubun** 2017-01-14 00:56 UTC

**Comment by sachin21** [comment] 2017-01-14 07:51
Okay. Today, I found temporary solution that is adding classes to `class_only: %w(google-chrome slack mikutter.rb)`. I'm okay for now.
Thank you very much. I'm waiting for the good news.
