### ISSUE TITLE
[bug report] couldn't remap keys

### ISSUE THREAD

**Issue by sachin21** [k0kubun/xremap#20] opened 2017-06-07 15:06 UTC
# Summary
From Yesterday, I can't emacs bindings with Chrome and Slack Linux app.
I don't know the trigger of this problem.

### Steps
- 1 lanuch xremap with config
- 2 launch `google-chrome-stable`.
- 3 Swtich to google-chrome from `xfce4-terminal`.
- 4 Input `ctrl + e`.
- 5 Switch to` xfce4-terminal`.

### Logs
```
$ xremap .xremap
Config loaded: #<Xremap::Config:0x207e1f0 @remaps_by_window={#<struct Xremap::Config::Window class_only=["google-chrome"], class_not=[]>=>[#<struct from_key=#<struct Xremap::Config::Key keysym=98, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65361, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=102, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65363, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=112, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65362, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=110, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65364, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=98, modifier=8, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65361, modifier=4, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=102, modifier=8, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65363, modifier=4, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=97, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65360, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=101, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65367, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=107, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65367, modifier=1, action=:input>, #<struct Xremap::Config::Key keysym=65535, modifier=0,action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=100, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65535, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=100, modifier=8, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65535, modifier=4, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=117, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65360, modifier=1, action=:input>, #<struct Xremap::Config::Key keysym=65535, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=119, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65361, modifier=5, action=:input>, #<struct Xremap::Config::Key keysym=65535, modifier=0, action=:input>]>]}, @config_dir="/home/sachin21dev">                                                                                                                                                     
remapped for class: "xfce4-terminal"
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
remapped for class: "google-chrome"
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
remapped for class: "xfce4-terminal"
```
### xremap's configurations
```
window class_only: %w(google-chrome slack) do
  remap 'C-b', to: 'Left'
  remap 'C-f', to: 'Right'
  remap 'C-p', to: 'Up'
  remap 'C-n', to: 'Down'

  remap 'M-b', to: 'Ctrl-Left'
  remap 'M-f', to: 'Ctrl-Right'

  remap 'C-a', to: 'Home'
  remap 'C-e', to: 'End'

  remap 'C-k', to: ['Shift-End', 'Delete']

  remap 'C-d', to: 'Delete'
  remap 'M-d', to: 'Ctrl-Delete'

  remap 'C-u', to: ['Shift-Home', 'Delete']
  remap 'C-w', to: ['Ctrl-Shift-Left', 'Delete']
end
```

### System information

- `uname -a` 
  - `Linux sachin21dev 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux`

- xremap's latest commit hash
  - https://github.com/k0kubun/xremap/commit/64eef405a64973fc3ff4299d83a10311a44b8246
- Google Chrome's version
  - `57.0.2987.133`

**Comment by k0kubun** [comment] 2017-06-07 15:27
Thank you for reporting. I need to research which event is "(33)", fix [here](https://github.com/k0kubun/xremap/blob/64eef405a64973fc3ff4299d83a10311a44b8246/tools/xremap/main.c#L11) to collect all available logs and ask you to see those logs. 

But I'm busy to work on another task and it'll be after that. Please wait a moment, or doing the above things will help.

**Comment by k0kubun** [comment] 2017-06-07 15:28
Also I want to know whether it works in old revisions (like before https://github.com/k0kubun/xremap/pull/19) or not.

**Comment by k0kubun** [comment] 2017-06-07 15:34
And all other things I want to say are written in https://github.com/k0kubun/xremap/issues/13. This looks very similar to the issue and maybe there's nothing I can do for this because it wasn't reproductive on my environment. I need to ask yourself to identify what's the trigger. This problem may depend on things which aren't related to xremap.

**Comment by k0kubun** [comment] 2017-06-07 15:38
In addition, you should make **reproductive script in minimal size** whenever you report a bug to any project. Obviously your "xremap's configurations" contain too many lines. Please provide only essential ones to distinguish the problem.

**Comment by sachin21** [comment] 2017-06-08 03:47
Thank you for the very quickly response.

> Thank you for reporting. I need to research which event is "(33)", fix here to collect all available logs and ask you to see those logs.

Uh, I'm not familiar with C lang. So could you tell me how-to-fix that error handler when you get some time?

> Obviously your "xremap's configurations" contain too many lines. Please provide only essential ones to distinguish the problem.

I'm really sorry. I updated the description with the minimal configuration that according to your advice.

> Also I want to know whether it works in old revisions (like before #19) or not.

It does not work. but error logs is different between https://github.com/k0kubun/xremap/commit/64eef405a64973fc3ff4299d83a10311a44b8246  and https://github.com/k0kubun/xremap/commit/2d3eefbf1e070bb2f8da9902f3cd31451871fe5f

# Report

This repot's configuration is same as above description's configuration.

## Steps

- Launch xremap with description's configuration
- Launch `google-chrome-stable`
- Switch to Chrome
- Input `ctrl + e`
- Switch to xfce4-terminal

## Logs

```
$ xremap .xremap                                                                                                                                                             [2.3.3 (global)]
Config loaded: #<Xremap::Config:0x207e1f0 @remaps_by_window={#<struct Xremap::Config::Window class_only=["google-chrome"], class_not=[]>=>[#<struct from_key=#<struct Xremap::Config::Key keysym=98, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65361, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=102, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65363, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=112, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65362, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=110, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65364, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=98, modifier=8, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65361, modifier=4, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=102, modifier=8, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65363, modifier=4, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=97, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65360, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=101, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65367, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=107, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65367, modifier=1, action=:input>, #<struct Xremap::Config::Key keysym=65535, modifier=0,action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=100, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65535, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=100, modifier=8, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65535, modifier=4, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=117, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65360, modifier=1, action=:input>, #<struct Xremap::Config::Key keysym=65535, modifier=0, action=:input>]>, #<struct from_key=#<struct Xremap::Config::Key keysym=119, modifier=4, action=:input>, to_keys=[#<struct Xremap::Config::Key keysym=65361, modifier=5, action=:input>, #<struct Xremap::Config::Key keysym=65535, modifier=0, action=:input>]>]}, @config_dir="/home/sachin21dev">
remapped for class: false
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
remapped for class: "google-chrome"
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
unexpected event detected! (33)
remapped for class: false
```

**Comment by k0kubun** [comment] 2017-06-08 13:18
> It does not work. but error logs is different between 64eef40 and 2d3eefb

Thanks for researching it. Such kind of information is helpful to solve the problem.

I use Google Chrome 58.0.3029.110, which is newer than yours and xremap works. So it's not a bug in xremap and another third party software including xfce4-terminal prevents it from working.

You can do further investigation even if you don't write C code. You should try another terminal, and distinguish what's the root cause of your problem. At least your bug report shouldn't include multiple third party software (chrome and xfce4-terminal). Two of xremap and one software is maximum. If it really needs two other softwares, obviously it includes the third party issue and you shouldn't report it here.

One very effective way to solve your problem is preparing another new environment with your Linux distribution and install only Chrome and xremap. Don't install any configuration files other than xremap's one. Then introduce xfce4-terminal, then other configuration files... step by step. And stop when it's reproductive and break the environment again, and reproduce in minimum condition. If you can't distinguish problems by yourself, you should take such kind of effort to solve it. If I'm in your situation, I'll definitely do that thing.

**Comment by sachin21** [comment] 2017-06-10 17:17
Oh, sorry. I just went to say I couldn't use Emacs keybindings on Google Chrome.
I forgot to write it. I"m really sorry. It doesn't matter with xfce4-terminal. but occurring problem on Google Chrome and Slack.

**Comment by sachin21** [comment] 2017-06-10 17:45
If the environment causes, xremap should pretty error messages for investigating.
I can't investigate. and you. I would be glad if you improve error messages and improve xremap.

Even If you want to say this is not a bug in xremap, I don't create the issue and report problems of xremap.
I really like xremap, but xremap seems can't stand to practical use. I look forward to standing to practical use.

**Comment by k0kubun** [comment] 2017-06-14 10:39
I see. Then the main problem is https://github.com/k0kubun/xremap/issues/14 and closing this for duplication.

> xremap seems can't stand to practical use.

I'm very sad to hear that :cry:

> I look forward to standing to practical use.

A similar tool whose backend is a little different is https://github.com/kui/rbindkeys. I prefer xremap's DSL but essentially it has more features than xremap. In addition, it touches more low layer (there are trade-offs, thus I created xremap). So there's possibility that rbindkeys works but xremap doesn't. So I recommend you to try it.

Anyway I'll implement proper logging after my current project is done... Again, very sorry...

**Closed by k0kubun** 2017-06-14 10:39 UTC

**Comment by acro5piano** [comment] 2017-06-15 03:39
@k0kubun 
I use xremap everyday for remapping Chromium. 
Xremap is really helpful and practical at least in my case!!

> xremap seems can't stand to practical use.

Although Xremap has some bug and problem, it helps a lot of linux desktop lovers to improve their productivity.
I prefer xremap's DSL to rbindkeys and other remapping tools.

I hope Xremap to be more stable and more people use it. And I'll try to improve it by sending patches.
Thank you very much for creating this software.

**Comment by sachin21** [comment] 2017-06-19 08:28
Sorry, I add more information.

My Chrome version is `57.0.2987.133`. So this issue is not related to https://twitter.com/k0kubun/status/876459836409397248 .
