### ISSUE TITLE
`CapsLock -> ZenkakuHankaku` remap doesn't work

### ISSUE THREAD

**Issue by komamitsu** [k0kubun/xremap#230] opened 2023-01-14 11:15 UTC
I'm trying xremap on Linux 6.0.12-76060006-generic x86_64 and X11, and noticed `CapsLock -> ZenkakuHankaku` remap doesn't work.

My config is as follows, and the other remaps work fine.

```yaml
modmap:
  - name: Global
    remap:
      CapsLock: ZenkakuHankaku
      Muhenkan: Ctrl_L
      KatakanaHiragana: Esc
keymap:
  - remap:
      C-h: Backspace
```

I checked what event happened  on `xev` when pushing `CapsLock` key while xremap was running
```
KeyRelease event, serial 28, synthetic NO, window 0x10800001,
    root 0x856, subw 0x0, time 7617058, (233,551), root:(283,739),
    state 0x0, keycode 93 (keysym 0x0, NoSymbol), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

I also noticed xremap outputs debug logs, so captured the output
```
[2023-01-14T10:05:38Z DEBUG xremap::event_handler] => 1: KEY_CAPSLOCK                                                                                                                         
[2023-01-14T10:05:38Z DEBUG xremap::action_dispatcher] 1: KEY_ZENKAKUHANKAKU                                                                                                                  
[2023-01-14T10:05:39Z DEBUG xremap::event_handler] => 0: KEY_CAPSLOCK                                                                                                                         
[2023-01-14T10:05:39Z DEBUG xremap::action_dispatcher] 0: KEY_ZENKAKUHANKAKU 
```

FYI: I used xkb for the key remap and it worked well https://gist.github.com/komamitsu/93cbda449186b9bc71dd29309edeed14.

Maybe I'm missing something. It would be great if there is any solution for the issue as I want to keep using this cool remap tool.

**Comment by k0kubun** [comment] 2023-01-15 04:45
> I also noticed xremap outputs debug logs, so captured the output

This output means, when CapsLock was pressed, it emitted a ZenkakuHankaku press, and when CapsLock was released, it emitted a ZenkakuHankaku release. It'd be the expected behavior for `CapsLock -> ZenkakuHankaku`. I tried your config and it correctly disables CapsLock (ZenkakuHankaku triggers nothing in my environment).

So, the current behavior seems like CapsLock is remapped to ZenkakuHankaku. What is your expected behavior? Did you keep an xremap process running while you were testing it?

**Comment by komamitsu** [comment] 2023-01-15 06:51
> What is your expected behavior?

My expectation was a ZenkakuHankaku key press event appears on `xev` like
```
KeyRelease event, serial 28, synthetic NO, window 0x3800001,
    root 0x856, subw 0x0, time 8238811, (288,631), root:(338,819),
    state 0x0, keycode 66 (keysym 0xff2a, Zenkaku_Hankaku), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
^ This is shown on `xev` when using the xkb-options (`caps:hztg` in https://gist.github.com/komamitsu/93cbda449186b9bc71dd29309edeed14)

But now I guess this issue comes from the different layers that xkb and xremap work. I found the following default configurations

- /usr/share/X11/xkb/keycodes/evdev
```
        //<HZTG> =  93; // Hankaku/Zenkakau toggle - not actually used
        alias <HZTG> = <TLDE>;
```

- /usr/share/X11/xkb/symbols/inet
```
// Commented out because HZTG has same keycode as TLDE
//    key <HZTG>   {      [ Zenkaku_Hankaku       ]       };
```

This is my poor guess, but these flows might happen.
- xkb remap: `keyboard (KEY: 66 (Capslock)) -> evdev (66) -> xkb (treat the 66 as ZenkakuHankaku)`
- xremap: `keyboard (KEY: 66 (Capslock)) -> evdev (66 -> 93 (ZenkakuHankaku)) -> xkb (??? 93 is unknown while I know 49 (TLDE))`

Anyway I've remaped Capslock to HiraganaKatakana instead of to ZenkakuHankaku and it's working well with some Mozc key config. I'll close this issue if you don't have any concern.

**Comment by k0kubun** [comment] 2023-01-15 07:26
Sounds good. An event device (evdev) and a uinput are the first layer, which xremap handles. xremap deliberately doesn't handle anything beyond that (except for application-based filtering), e.g. X events or X keyboard layouts. From what I'm seeing, it doesn't seem like the issue is on xremap's layer, so closing this as you suggested. Thanks!

**Closed by k0kubun** 2023-01-15 07:26 UTC
