### ISSUE TITLE
trigger issue 0.7.7.1

### ISSUE THREAD

**Issue by cipherlogs** [k0kubun/xremap#197] opened 2022-10-22 20:25 UTC
related to #154 

for example 

shift + win + k will trigger Win - k (which is up in my config)
ctrl + win + k will trigger win - k (which is up in my config)

```
keymap:
  - name: Global
    remap:
      WIN-k: up
```

**Comment by k0kubun** [comment] 2022-10-22 20:33
Can you write both the current behavior and the expected behavior? I don't understand which one you wrote.

**Comment by cipherlogs** [comment] 2022-10-22 20:52
the expected behaviour is to press shift + win + k instead of pressing win + k

**Comment by k0kubun** [comment] 2022-11-02 06:11
Sorry, that was a bad way to ask it. Can you provide the following three bullets? e.g.

* Input keys: Shift + Win + K
* Current behavior: Win + K
* Expected behavior: Shift + Win + K

If this is exactly what you meant, please copy-paste it as is.

**Comment by cipherlogs** [comment] 2022-11-02 15:02
Yes that's the exact behavior

* Input keys: Shift + Win + K
* Current behavior: Win + K
* Expected behavior: Shift + Win + K

**Comment by k0kubun** [comment] 2022-11-03 03:57
I can't reproduce your "Current behavior". This is my output of `RUST_LOG=debug xremap config.yml`:

```
[2022-11-03T03:52:24Z DEBUG xremap::event_handler] => 0: KEY_ENTER
[2022-11-03T03:52:24Z DEBUG xremap::action_dispatcher] 0: KEY_ENTER
[2022-11-03T03:52:26Z DEBUG xremap::event_handler] => 1: KEY_RIGHTMETA
[2022-11-03T03:52:26Z DEBUG xremap::action_dispatcher] 1: KEY_RIGHTMETA
[2022-11-03T03:52:26Z DEBUG xremap::event_handler] => 1: KEY_LEFTSHIFT
[2022-11-03T03:52:26Z DEBUG xremap::action_dispatcher] 1: KEY_LEFTSHIFT
[2022-11-03T03:52:26Z DEBUG xremap::event_handler] => 1: KEY_K
[2022-11-03T03:52:26Z DEBUG xremap::action_dispatcher] 0: KEY_RIGHTMETA
[2022-11-03T03:52:26Z DEBUG xremap::action_dispatcher] 1: KEY_UP
[2022-11-03T03:52:26Z DEBUG xremap::action_dispatcher] 0: KEY_UP
[2022-11-03T03:52:26Z DEBUG xremap::action_dispatcher] 1: KEY_RIGHTMETA
^[[1;2A[2022-11-03T03:52:26Z DEBUG xremap::event_handler] => 0: KEY_K
[2022-11-03T03:52:26Z DEBUG xremap::action_dispatcher] 0: KEY_K
[2022-11-03T03:52:26Z DEBUG xremap::event_handler] => 0: KEY_LEFTSHIFT
[2022-11-03T03:52:26Z DEBUG xremap::action_dispatcher] 0: KEY_LEFTSHIFT
[2022-11-03T03:52:26Z DEBUG xremap::event_handler] => 0: KEY_RIGHTMETA
[2022-11-03T03:52:26Z DEBUG xremap::action_dispatcher] 0: KEY_RIGHTMETA
```

and this is exactly the expected behavior. What this means is:

* Input keys: Shift + Win + K
* Current behavior: Shift + Up
* Expected behavior: Shift + Up

Can you run `RUST_LOG=debug xremap config.yml`, press Shift + Win + K, interrupt it with C-c, and share the entire output of the command here?

---

I'll close this one for now because this issue doesn't describe any problem on the xremap side currently, but please continue to leave comments on this issue. I'll reopen this when it describes xremap's issue and becomes actionable.

**Closed by k0kubun** 2022-11-03 03:57 UTC

**Comment by laech** [comment] 2022-12-04 22:27
> ```
> keymap:
>  - name: Global
>    remap:
>      WIN-k: up
>```

> and this is exactly the expected behavior. What this means is:
>
> * Input keys: Shift + Win + K
> * Current behavior: Shift + Up
> * Expected behavior: Shift + Up

I was surprised by this behavior too probably because I'm used to the way how xkeynail works, in xkeynail <kbd>shift+win+k</kbd> will just output <kbd>shift+win+k</kbd> because there is no explicit mapping for that combo in the config, compare to xremap which will automatically map <kbd>shift+win+k</kbd> to <kbd>shift+up</kbd> because of <kbd>win+k</kbd> is mapped to <kbd>up</kbd>, which is handy in this case but creates the opposite inconvenience - I have <kbd>ctrl+s</kbd> mapped to <kbd>ctrl+f</kbd>, now if I press <kbd>ctrl+alt+s</kbd> it automatically maps it <kbd>ctrl+alt+f</kbd> which is not what I want, so I would have to explicitly unmap all other modifiers for <kbd>ctrl+s</kbd>.

**Comment by k0kubun** [comment] 2022-12-05 04:43
You have to fight with the use case of https://github.com/k0kubun/xremap/issues/102 or introduce a (maybe per-keymap) option to enable that behavior.

**Comment by laech** [comment] 2022-12-05 08:39
Okay I'll see if I can add an option for it.

**Comment by U1s2e3r4n5a6m7e** [comment] 2022-12-07 15:13
Thank you @laech Now I can use my DWM workflow again with xremap. I'm so grateful for this 🎉
